# Generated by Django 2.1 on 2020-01-25 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0002_vote'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='vote',
            managers=[
            ],
        ),
    ]
