# Generated by Django 2.1 on 2020-02-01 03:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thread', '0003_auto_20200125_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png'])], verbose_name='投稿画像'),
        ),
    ]
